<?php

namespace Yiendos\MySitesIde\Monitoring\Grafana;

/**
 * The dashboards shipped in the plugin's dashboards/<service>/, provisioned
 * for whichever of the other monitoring plugins are installed - each set
 * queries that plugin's data source by its fixed UID (see Datasources).
 *
 * They're copied into storage/plugins/grafana/dashboards/<folder>/, which
 * Grafana watches: a set whose plugin has been removed is deleted, and
 * Grafana removes its dashboards with it. That folder is the plugin's own -
 * changes made in Grafana have to be saved as a copy.
 */
final class Dashboards
{
    /**
     * Compose service => the Grafana folder its dashboards go in
     */
    public const SETS = [
        'prometheus' => 'Containers',
    ];

    /**
     * Where the dashboards are copied, under storage/plugins/grafana/
     */
    public const STORAGE = 'dashboards';

    /**
     * @param array<string, bool> $installed compose service => whether a plugin provides it
     */
    public function __construct(private array $installed)
    {
    }

    /**
     * Reads which monitoring plugins are installed from the IDE
     *
     * @return self
     */
    public static function fromIde(): self
    {
        return new self(array_map(Ide::installed(...), array_combine(array_keys(self::SETS), array_keys(self::SETS))));
    }

    /**
     * The dashboards to provision, as folder/file.json => the shipped file
     *
     * @return array<string, string>
     */
    public function files(): array
    {
        $files = [];

        foreach (self::SETS as $service => $folder) {
            if (!($this->installed[$service] ?? false)) {
                continue;
            }

            foreach (glob(Ide::package("dashboards/{$service}/*.json")) ?: [] as $file) {
                $files[$folder . '/' . basename($file)] = $file;
            }
        }

        ksort($files);

        return $files;
    }

    /**
     * The Grafana folders that will have dashboards in them
     *
     * @return string[]
     */
    public function folders(): array
    {
        return array_values(array_unique(array_map(fn (string $path): string => dirname($path), array_keys($this->files()))));
    }

    /**
     * The provisioning file, dashboards/my-sites-ide.yaml - one provider over
     * storage's dashboards/, each subfolder a Grafana folder. Grafana checks
     * the files every 10 seconds, so dashboards come and go without a restart.
     *
     * @return string
     */
    public function yaml(): string
    {
        $path = '/storage/' . self::STORAGE;

        return <<<YAML
        # Generated by monitoring:grafana-start - do not edit. The dashboards come from the plugin's
        # dashboards/, for the monitoring plugins installed.
        apiVersion: 1

        providers:
          - name: my-sites-ide
            orgId: 1
            type: file
            disableDeletion: false
            allowUiUpdates: false
            updateIntervalSeconds: 10
            options:
              path: {$path}
              foldersFromFilesStructure: true

        YAML;
    }

    /**
     * Copies the dashboards into storage and removes any that are no longer
     * provisioned (or empty folders left behind)
     *
     * @return void
     */
    public function sync(): void
    {
        $wanted = $this->files();

        foreach ($wanted as $path => $file) {
            Ide::write(self::STORAGE . "/{$path}", (string) file_get_contents($file));
        }

        $storage = Ide::storage(self::STORAGE);

        foreach (glob("{$storage}/*/*.json") ?: [] as $file) {
            if (!isset($wanted[basename(dirname($file)) . '/' . basename($file)])) {
                unlink($file);
            }
        }

        foreach (glob("{$storage}/*", GLOB_ONLYDIR) ?: [] as $folder) {
            if ((glob("{$folder}/*") ?: []) === []) {
                rmdir($folder);
            }
        }
    }
}
