<?php

namespace Yiendos\MySitesIde\Monitoring\Grafana;

/**
 * Grafana's data sources, built from whichever of the other monitoring plugins
 * are installed, as a provisioning file. Each one links to the others where it
 * can: Tempo traces to their Loki logs and Prometheus metrics, Loki log lines
 * and Prometheus exemplars back to their trace.
 *
 * The UIDs are fixed, so the links survive a rewrite and dashboards can refer
 * to them. A plugin that's been removed has its data source deleted rather
 * than left behind pointing at nothing - Grafana keeps provisioned data
 * sources in its database until told otherwise.
 */
final class Datasources
{
    /**
     * Data source name => compose service, in the order they're listed (the
     * first installed one is Grafana's default)
     */
    public const SOURCES = [
        'Prometheus' => 'prometheus',
        'Loki' => 'loki',
        'Tempo' => 'tempo',
    ];

    /**
     * @param array<string, bool> $installed compose service => whether a plugin provides it
     */
    public function __construct(private array $installed)
    {
    }

    /**
     * Reads which monitoring plugins are installed from the IDE
     *
     * @return self
     */
    public static function fromIde(): self
    {
        return new self(array_map(Ide::installed(...), array_combine(self::SOURCES, self::SOURCES)));
    }

    /**
     * The names of the data sources that will be provisioned
     *
     * @return string[]
     */
    public function names(): array
    {
        return array_keys(array_filter(self::SOURCES, fn (string $service): bool => $this->has($service)));
    }

    /**
     * The provisioning file, datasources/my-sites-ide.yaml
     *
     * @return string
     */
    public function yaml(): string
    {
        $yaml = "# Generated by monitoring:grafana-start from the monitoring plugins installed - do not edit.\n"
            . "apiVersion: 1\n";

        $removed = array_diff(array_keys(self::SOURCES), $this->names());

        if ($removed !== []) {
            $yaml .= "\ndeleteDatasources:\n";

            foreach ($removed as $name) {
                $yaml .= "  - name: {$name}\n    orgId: 1\n";
            }
        }

        $sources = array_filter([
            $this->has('prometheus') ? $this->prometheus() : null,
            $this->has('loki') ? $this->loki() : null,
            $this->has('tempo') ? $this->tempo() : null,
        ]);

        if ($sources === []) {
            return $yaml;
        }

        $yaml .= "\ndatasources:\n";
        $default = true;

        foreach ($sources as $source) {
            // the first installed source becomes the default, the one Explore opens on
            $yaml .= str_replace('__DEFAULT__', $default ? 'true' : 'false', $source);
            $default = false;
        }

        return $yaml;
    }

    /**
     * @param string $service
     * @return bool
     */
    private function has(string $service): bool
    {
        return $this->installed[$service] ?? false;
    }

    /**
     * @return string
     */
    private function prometheus(): string
    {
        $yaml = <<<'YAML'
          - name: Prometheus
            type: prometheus
            uid: prometheus
            url: http://prometheus:9090
            access: proxy
            isDefault: __DEFAULT__
            editable: false
            jsonData:
              httpMethod: POST

        YAML;

        if ($this->has('tempo')) {
            // exemplars on Tempo's span metrics carry the trace they came from
            $yaml .= <<<'YAML'
                  exemplarTraceIdDestinations:
                    - name: trace_id
                      datasourceUid: tempo

            YAML;
        }

        return $yaml;
    }

    /**
     * @return string
     */
    private function loki(): string
    {
        $yaml = <<<'YAML'
          - name: Loki
            type: loki
            uid: loki
            url: http://loki:3100
            access: proxy
            isDefault: __DEFAULT__
            editable: false
            jsonData:
              maxLines: 1000

        YAML;

        if ($this->has('tempo')) {
            // OTLP logs keep their trace_id as structured metadata; $$ stops Grafana
            // expanding ${__value.raw} as an environment variable
            $yaml .= <<<'YAML'
                  derivedFields:
                    - name: trace_id
                      matcherType: label
                      matcherRegex: trace_id
                      datasourceUid: tempo
                      url: "$${__value.raw}"
                      urlDisplayLabel: View trace

            YAML;
        }

        return $yaml;
    }

    /**
     * @return string
     */
    private function tempo(): string
    {
        $yaml = <<<'YAML'
          - name: Tempo
            type: tempo
            uid: tempo
            url: http://tempo:3200
            access: proxy
            isDefault: __DEFAULT__
            editable: false
            jsonData:
              nodeGraph:
                enabled: true
              streamingEnabled:
                search: true
                metrics: true

        YAML;

        if ($this->has('prometheus')) {
            // Tempo's metrics-generator writes service graphs and span metrics to Prometheus
            $yaml .= <<<'YAML'
                  serviceMap:
                    datasourceUid: prometheus
                  tracesToMetrics:
                    datasourceUid: prometheus
                    spanStartTimeShift: "-5m"
                    spanEndTimeShift: "5m"

            YAML;
        }

        if ($this->has('loki')) {
            $yaml .= <<<'YAML'
                  tracesToLogsV2:
                    datasourceUid: loki
                    filterByTraceID: true
                    spanStartTimeShift: "-5m"
                    spanEndTimeShift: "5m"
                  lokiSearch:
                    datasourceUid: loki

            YAML;
        }

        return $yaml;
    }
}
